### ISSUE TITLE
Console error 2.9.7-1

### ISSUE THREAD

**Issue by successed** [poma123/PickupSpawners#13]
Can you fix this ?

```
[14:30:56 INFO]: [Core] Checking for 1 updates.[Core] Checking update for Core v0.2.4[PickupSpawners] The spawner breaker item (saved) is null. Please create an issue with the following stacktrace on github.com/poma123/PickupSpawners
[14:30:56 ERROR]: Could not pass event BlockBreakEvent to PickupSpawners vDEV - 8 (git aded4b16)
java.lang.NullPointerException: null
at me.poma123.spawners.Listener.isItemStacksGood(Listener.java:450) ~[?:?]
at me.poma123.spawners.Listener.onSpawnerBreak(Listener.java:587) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor344.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-32]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-32]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-32]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:313) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:80) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.EntityPlayer.tick(EntityPlayer.java:363) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:722) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.World.a(World.java:878) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:488) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1239) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-32]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-32]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Config : 
[config.txt](https://github.com/poma123/PickupSpawners/files/4023341/config.txt)

Server version 1.15.1 paper 32
PickupSpawners version : pickupspawners-2.9.7-1

**Comment by poma123** [comment]
You didn't configure any spawner breaker items at all. How would you pick up spawners in that way?

**Comment by successed** [comment]
> You didn't configure any spawner breaker items at all. How would you pick up spawners in that way?

I don't want to take spawners. You do not offer a spawner take limit per player.

**Comment by poma123** [comment]
You don't want to get (break then get the item) or place them?

**Comment by successed** [comment]
> You don't want to get (break then get the item) or place them?

No, I just want to place it. Because there is no limit per person to break and place.

**Comment by poma123** [comment]
Okay then, i'm working on this

**Comment by poma123** [comment]
There will be an update in 5 minutes
https://poma123.github.io/builds/poma123/PickupSpawners/master/
