### ISSUE TITLE
error

### ISSUE THREAD

**Issue by successed** [poma123/PickupSpawners#6]
[19:40:46 ERROR]: Could not pass event BlockBreakEvent to PickupSpawners v2.9.5
java.lang.NullPointerException: null
        at me.poma123.spawners.Listener.isItemStacksGood(Listener.java:379) ~[?:?]
        at me.poma123.spawners.Listener.onSpawnerBreak(Listener.java:498) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor307.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:84) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.EntityPlayer.tick(EntityPlayer.java:355) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by poma123** [comment]
I think breaking a spawner by hand cause this issue.
Fix in the next release.
